version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run: pip install --upgrade pip --user
      - run: pip3 install -r requirements.txt
      - run: |
          psql -d $TEST_DATABASE_URL -c "CREATE TABLE test (name char(25));"
      - run: |
          psql -d $TEST_DATABASE_URL -c "INSERT INTO test VALUES ('Wiley'), ('Eriksen'), ('Kanta');"
      - run: |
          psql -d $TEST_DATABASE_URL -c "SELECT * from test"
      - run:
          name: Run User Unit Test
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
